---

- name: Ensure rsyslog-gnutls is installed on Debian flavours
  apt:
    name: rsyslog-gnutls
    state: "{{ 'latest' if papertrail_pkg_mgr_install_latest else 'present' }}"
  when: ansible_pkg_mgr == 'apt' and papertrail_install_rsyslog_gnutls
  become: true

- name: Ensure rsyslog-gnutls is installed on CentOS flavours
  yum:
    name: rsyslog-gnutls
    state: "{{ 'latest' if papertrail_pkg_mgr_install_latest else 'present' }}"
  when: ansible_pkg_mgr == 'yum' and papertrail_install_rsyslog_gnutls
  become: true

- include: certificate-file.yml
  when: papertrail_rsyslog_tls_cert_bundle_download_path is defined

- include: certificate-var.yml
  when: papertrail_rsyslog_tls_cert_bundle_do_not_use_var is not defined

- name: Stat the certificate
  stat:
    get_checksum: yes
    get_md5: yes
    path: "{{ papertrail_rsyslog_tls_cert_bundle_path }}"
  register: papertrail_rsyslog_tls_cert_bundle_stat
  when: papertrail_rsyslog_tls_cert_bundle_checksum is defined
  become: true

- name: Check the checksum against the stat
  fail:
    msg: "Checksum for certificate {{ papertrail_rsyslog_tls_cert_bundle_path }} do not match"
  when: |
    papertrail_rsyslog_tls_cert_bundle_checksum is defined
    and papertrail_rsyslog_tls_cert_bundle_stat.stat.md5 != papertrail_rsyslog_tls_cert_bundle_checksum

- name: Set whether or not to use local queueing based on secure setting
  set_fact:
    papertrail_rsyslog_queue: yes
  when: papertrail_rsyslog_queue is not defined
...
