---
- name: Ensure rsyslog is installed on Debian flavours
  apt:
    name: rsyslog
    state: "{{ 'latest' if papertrail_pkg_mgr_install_latest else 'present' }}"
    update_cache: "{{ papertrail_pkg_mgr_update_cache }}"
  when: ansible_pkg_mgr == 'apt' and papertrail_install_rsyslog
  become: true

- name: Ensure rsyslog is installed on CentOS flavours
  yum:
    name: rsyslog
    state: "{{ 'latest' if papertrail_pkg_mgr_install_latest else 'present' }}"
    update_cache: "{{ papertrail_pkg_mgr_update_cache }}"
  when: ansible_pkg_mgr == 'yum' and papertrail_install_rsyslog
  become: true

- name: Make the rsyslog.d directory
  file:
    path: "{{ papertrail_rsyslogd_conf_dir }}"
    state: directory
    mode: "{{ papertrail_rsyslogd_conf_dir_mode }}"
    owner: "{{ papertrail_rsyslogd_conf_dir_owner }}"
    group: "{{ papertrail_rsyslogd_conf_dir_group }}"
    recurse: "{{ papertrail_rsyslogd_conf_dir_recurse }}"
  become: true

- name: Copy the template into place
  template:
    src: "{{ papertrail_rsyslog_conf_file_template }}"
    dest: "{{ papertrail_rsyslog_conf_file }}"
    mode: "{{ papertrail_rsyslogd_conf_file_mode }}"
    owner: "{{ papertrail_rsyslogd_conf_file_owner }}"
    group: "{{ papertrail_rsyslogd_conf_file_group }}"
  when: papertrail_rsyslog_conf_file_template is defined
  notify:
    - restart rsyslog
  become: true


- name: Ensure the rsyslog.d directory is included
  lineinfile:
    state: present
    dest: "{{ papertrail_rsyslog_conf_file }}"
    line: "$IncludeConfig {{ papertrail_rsyslogd_conf_dir }}/*.conf"
  notify:
    - restart rsyslog

- name: Set up the certificate bundle and requirements if using secure mode
  include: certificate.yml
  when: papertrail_rsyslog_secure
  notify:
    - restart rsyslog

- name: Create the work directory for rsyslog
  file:
    path: "{{ papertrail_rsyslog_work_dir }}"
    state: directory
    mode: "{{ papertrail_rsyslog_work_dir_mode | default('0644') }}"
    owner: "{{ papertrail_rsyslog_work_dir_owner | default('root') }}"
    group: "{{ papertrail_rsyslog_work_dir_group | default('root') }}"
    recurse: "{{ papertrail_rsyslog_work_dir_recurse | default( 'no') }}"
  when: papertrail_rsyslog_work_dir is defined
  notify:
    - restart rsyslog
  become: true

- name: Put the papertrail config into the rsyslog.d directory
  template:
    src: "{{ papertrail_rsyslog_template }}"
    dest: "{{ papertrail_rsyslog_file }}"
    mode: "{{ papertrail_rsyslogd_file_mode }}"
    owner: "{{ papertrail_rsyslogd_file_owner }}"
    group: "{{ papertrail_rsyslogd_file_group  }}"
  notify:
    - restart rsyslog
  become: true

...
